before_script:
  - eval $(ssh-agent -s)
  - git config user.name "Streamlio CI"
  - git config user.email "ssg-streamlio@splunk.com"
  - ulimit -c unlimited
  - export MAVEN_OPTS="-Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd'T'HH:mm:ss.SSSZ -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO"

cache:
  paths:
    - /root/.m2/repository

variables:
  DOCKER_IMAGE: "aahmedse/maven"
  DOCKER_TAG: "3.6.1-jdk-8-dind"
  PYPI_URL: "https://repo.splunk.com/artifactory/api/pypi/pypi"
  PLAYGROUND_DOCKER_REGISTRY: cloudrepo-docker-playground.jfrog.io
  PRODUCTION_DOCKER_REGISTRY: cloudrepo-docker.jfrog.io
  PLAYGROUND_DOCKER_PATH: docker:v1/play/prefix/maas
  PRODUCTION_DOCKER_PATH: docker:v1/prod/prefix/maas

stages:
  - deploy-manual
  - ci
  - deploy

# == Python Build Job Start

release_pypi_manylinux3.7:
  image: apachepulsar/pulsar-build:manylinux-cp37-cp37m
  stage: deploy-manual
  cache: {}
  script:
    - export USE_FULL_POM_NAME=True
    - cd pulsar-client-cpp
    - cmake . -DPYTHON_INCLUDE_DIR=/opt/python/cp37-cp37m/include/python3.7 -DPYTHON_LIBRARY=/opt/python/cp37-cp37m/lib -DLINK_STATIC=ON -DBUILD_TESTS=OFF
    - make -j8 _pulsar
    - cd python
    - python3 setup.py bdist_wheel
    - auditwheel repair dist/pulsar_client-*-$PYTHON_SPEC-linux_x86_64.whl
    - twine upload --verbose --skip-existing --repository-url "${PYPI_URL}" dist/*.whl -u "${STREAMLIO_ARTIFACTORY_USERNAME}" -p "${STREAMLIO_ARTIFACTORY_PASSWORD}"
  when: manual

# == Python Build Job End

tag_release:
  image: apachepulsar/pulsar-build:latest
  stage: deploy
  only:
    - branch-2.4-streamlio
    - branch-2.5-streamlio
  script:
    - build/splunk-tag-release.sh

checkin_unit:
  image: apachepulsar/pulsar-build:latest
  stage: ci
  timeout: 180 mins
  only:
    - merge_requests
  script:
    - dev/monitor-mvn &
    - timeout 170m mvn -fae -B --show-version -ntp install -DtestForkCount=1 -DtestReuseFork=false
  after_script:
    - date
    - tar zcf test-results.tgz */target/surefire-reports/
    - echo "[START_TEST_SUMMARY]"
    - build/testsummary.py */target/surefire-reports/TEST-*.xml
    - echo "[END_TEST_SUMMARY]"
    - build/testtrim.py $(find . -name 'TEST*.xml')
  artifacts:
    paths:
      - test-results.tgz
      - process-debug.log
    expire_in: 100 days
    when: always
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"

checkin_cpp:
  image: apachepulsar/pulsar-build:latest
  stage: ci
  timeout: 180 mins
  only:
    - merge_requests
  script:
    - mvn -B --show-version -ntp package -DskipTests
    - /bin/bash -c "cd pulsar-client-cpp && cmake . -DCMAKE_BUILD_TYPE=Debug && make check-format && make -j8"
    - /bin/bash -c "cd pulsar-client-cpp && ./run-unit-tests.sh"
  after_script:
    - cp -r /tmp/pulsar-test-dist/logs broker-logs
    - cp /tmp/*core* .
  artifacts:
    paths:
      - broker-logs/
      - "pulsar-client-cpp/tests/main"
      - "pulsar-client-cpp/tests/*core*"
      - "pulsar-client-cpp/lib/libpulsar.so.*"
      - "pulsar-client-cpp/lib/libpulsar.so"
      - "pulsar-client-cpp/python/_pulsar.so"
      - "*core*"
    expire_in: 100 days
    when: always

release_artifacts:
  image: $DOCKER_IMAGE:$DOCKER_TAG
  stage: deploy
  timeout: 60 mins
  only:
    - /^release-.*$/
  script:
    - mvn -B --show-version -ntp install -DskipTests
    - ./release_maven.sh

release_alpine_apk:
  image: apachepulsar/pulsar-build:alpine-3.11
  stage: deploy
  cache: {}
  only:
    - /^release-.*$/
  script:
    - ./pulsar-client-cpp/pkg/apk/build-apk.sh
    - VERSION=$(python3 src/get-project-version.py | sed -E 's/-[a-z]+-/./' | sed -E 's/.[A-Z]+././')
    - URL=https://repo.splunk.com/artifactory/maven-splunk/com/splunk/pulsar/pulsar-client-alpine
    - CREDENTIALS="-u $STREAMLIO_ARTIFACTORY_USERNAME:$STREAMLIO_ARTIFACTORY_PASSWORD"
    - DIST_DIR=./pulsar-client-cpp/pkg/apk/pkg/x86_64/
    - curl ${CREDENTIALS} --upload-file ${DIST_DIR}/apache-pulsar-client-${VERSION}-r0.apk \
        ${URL}/${VERSION}/apache-pulsar-client-${VERSION}-r0.apk
    - curl ${CREDENTIALS} --upload-file ${DIST_DIR}/apache-pulsar-client-dev-${VERSION}-r0.apk \
        ${URL}/${VERSION}/apache-pulsar-client-dev-${VERSION}-r0.apk
    - curl ${CREDENTIALS} --upload-file ${DIST_DIR}/APKINDEX.tar.gz ${URL}/${VERSION}/APKINDEX.tar.gz

release_alpine_python_wheel:
  image: apachepulsar/pulsar-build:alpine-3.11
  stage: deploy
  cache: {}
  only:
    - /^release-.*$/
  script:
    - export USE_FULL_POM_NAME=True
    - export NAME_POSTFIX='-alpine'
    - ./pulsar-client-cpp/docker/alpine/build-wheel-file-within-docker.sh
    - twine upload --verbose --skip-existing --repository-url "${PYPI_URL}"./pulsar-client-cpp/python/dist/*.whl -u "${STREAMLIO_ARTIFACTORY_USERNAME}" -p "${STREAMLIO_ARTIFACTORY_PASSWORD}"
