before_script:
  - eval $(ssh-agent -s)
  - git config user.name "Streamlio CI"
  - git config user.email "ssg-streamlio@splunk.com"

cache:
  paths:
    - /root/.m2/repository

variables:
  DOCKER_IMAGE: "aahmedse/maven"
  DOCKER_TAG: "3.6.1-jdk-8-dind"
  PYPI_URL: "https://repo.splunk.com/artifactory/api/pypi/pypi"

stages:
  - deploy-manual
  - ci
  - deploy

# Python Build Job Start

release_pypi_alpine3.6:
  image: apachepulsar/pulsar-build:3.6-alpine3.9
  stage: deploy-manual
  cache: {}
  script:
    - export USE_FULL_POM_NAME=True
    - export NAME_POSTFIX=-alpine
    - cd pulsar-client-cpp
    - cmake . -DBUILD_TESTS=OFF -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m
    - make -j8 _pulsar
    - cd python
    - python3 setup.py bdist_wheel
    - twine upload --verbose --skip-existing --repository-url "${PYPI_URL}" dist/*.whl -u "${STREAMLIO_ARTIFACTORY_USERNAME}" -p "${STREAMLIO_ARTIFACTORY_PASSWORD}"
  when: manual

release_pypi_alpine3.7:
  image: apachepulsar/pulsar-build:3.7-alpine3.10
  stage: deploy-manual
  cache: {}
  script:
    - export USE_FULL_POM_NAME=True
    - export NAME_POSTFIX=-alpine
    - cd pulsar-client-cpp
    - cmake . -DBUILD_TESTS=OFF -DPYTHON_INCLUDE_DIR=/usr/include/python3.7m
    - make -j8 _pulsar
    - cd python
    - python3 setup.py bdist_wheel
    - twine upload --verbose --skip-existing --repository-url "${PYPI_URL}" dist/*.whl -u "${STREAMLIO_ARTIFACTORY_USERNAME}" -p "${STREAMLIO_ARTIFACTORY_PASSWORD}"
  when: manual

release_pypi_alpine3.8:
  image: apachepulsar/pulsar-build:3.8-alpine3.11
  stage: deploy-manual
  cache: {}
  script:
    - export USE_FULL_POM_NAME=True
    - export NAME_POSTFIX=-alpine
    - cd pulsar-client-cpp
    - cmake . -DBUILD_TESTS=OFF -DPYTHON_INCLUDE_DIR=/usr/include/python3.8
    - make -j8 _pulsar
    - cd python
    - python3 setup.py bdist_wheel
    - twine upload --verbose --skip-existing --repository-url "${PYPI_URL}" dist/*.whl -u "${STREAMLIO_ARTIFACTORY_USERNAME}" -p "${STREAMLIO_ARTIFACTORY_PASSWORD}"
  when: manual

release_pypi_manylinux3.7:
  image: apachepulsar/pulsar-build:manylinux-cp37-cp37m
  stage: deploy-manual
  cache: {}
  script:
    - export USE_FULL_POM_NAME=True
    - cd pulsar-client-cpp
    - cmake . -DPYTHON_INCLUDE_DIR=/opt/python/cp37-cp37m/include/python3.7 -DPYTHON_LIBRARY=/opt/python/cp37-cp37m/lib -DLINK_STATIC=ON -DBUILD_TESTS=OFF
    - make -j8 _pulsar
    - cd python
    - python3 setup.py bdist_wheel
    - auditwheel repair dist/pulsar_client-*-$PYTHON_SPEC-linux_x86_64.whl
    - twine upload --verbose --skip-existing --repository-url "${PYPI_URL}" dist/*.whl -u "${STREAMLIO_ARTIFACTORY_USERNAME}" -p "${STREAMLIO_ARTIFACTORY_PASSWORD}"
  when: manual

# Python Build Job End

tag_release:
  image: apachepulsar/pulsar-build:latest
  stage: deploy
  only:
    - branch-2.4-streamlio
    - branch-2.5-streamlio
  script:
    - build/splunk-tag-release.sh

checkin_unit:
  image: apachepulsar/pulsar-build:latest
  stage: ci
  timeout: 180 mins
  only:
    - merge_requests
    - branch-2.4-streamlio
    - branch-2.5-streamlio
    - /^release-.*$/
  script:
    - mvn -fae -B -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO --show-version -ntp install -DtestForkCount=1 -DtestReuseFork=false
  after_script:
    - tar zcf test-results.tgz */target/surefire-reports/
    - echo "[START_TEST_SUMMARY]"
    - build/testsummary.py */target/surefire-reports/TEST-*.xml
    - echo "[END_TEST_SUMMARY]"
    - build/testtrim.py $(find . -name 'TEST*.xml')
  artifacts:
    paths:
      - test-results.tgz
    expire_in: 100 days
    when: always
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"

checkin_cpp:
  image: apachepulsar/pulsar-build:latest
  stage: ci
  timeout: 120 mins
  only:
    - merge_requests
    - branch-2.4-streamlio
    - branch-2.5-streamlio
    - /^release-.*$/
  script:
    - mvn -B -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO --show-version -ntp package -DskipTests
    - /bin/bash -c "cd pulsar-client-cpp && cmake . -DCMAKE_BUILD_TYPE=Debug && make check-format && make -j8"
    - /bin/bash -c "cd pulsar-client-cpp && ./run-unit-tests.sh"
  after_script:
    - cp -r /tmp/pulsar-test-dist/logs broker-logs
  artifacts:
    paths:
      - broker-logs/
    expire_in: 100 days
    when: always

release_artifacts:
  image: $DOCKER_IMAGE:$DOCKER_TAG
  stage: deploy
  timeout: 60 mins
  only:
    - /^release-.*$/
  script:
    - mvn -B -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO --show-version -ntp install -DskipTests
    - ./release_maven.sh
