configs:
- name: globalZookeeperServers
  default: ''
- name: zooKeeperSessionTimeoutMillis
  default: '30000'
- name: serviceUrl
  default: ''
- name: serviceUrlTls
  default: ''
- name: brokerServiceUrl
  default: ''
- name: brokerServiceUrlTls
  default: ''
- name: webServicePort
  default: '8080'
- name: webServicePortTls
  default: '8443'
- name: bindAddress
  default: 0.0.0.0
- name: clusterName
  default: ''
- name: authenticationEnabled
  default: 'false'
- name: authenticationProviders
  default: ''
- name: authorizationEnabled
  default: 'false'
- name: superUserRoles
  default: ''
- name: brokerClientAuthenticationPlugin
  default: ''
- name: brokerClientAuthenticationParameters
  default: ''
- name: tlsEnabled
  default: 'false'
- name: tlsAllowInsecureConnection
  default: 'false'
- name: tlsCertificateFilePath
  default: ''
- name: tlsKeyFilePath
  default: ''
- name: tlsTrustCertsFilePath
  default: ''
